[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

[theme.templates]
builtin_ids = [ "alacritty", "gtk3", "gtk4", "helix", "kcolorscheme", "niri", "qt", "starship" ]
community_ids = [ "zed", "zellij" ]
