

[shell.panel]
clipboard_position = "auto"
control_center_placement = "floating"
launcher_placement = "floating"
launcher_position = "auto"
open_near_click_clipboard = true
open_near_click_control_center = true
open_near_click_wallpaper = true
polkit_position = "auto"
wallpaper_placement = "floating"

[shell.session]
grid = true

[shell.launcher]
app_grid = true

[shell]
niri_overview_type_to_launch_enabled = true
polkit_agent = true
